version: '3.8'
services:
  lieu-api:
    # build: ../si-lieu-api
    build: https://github.com/Flintpop/si-lieu-api.git
    ports: # mettre expose pour éviter que les ports soient exposés en dehors du réseau. core-api on pourra laisser en ports
      - "8082:8080"
    networks:
      - ubo-network

  commentaire-api:
    build:
      context: https://github.com/Flintpop/si-commentaire-api.git
    ports:
      - "8081:8080"
    networks:
      - ubo-network

  # event-api:
  #   build: 
  #     context: https://github.com/Flintpop/si-event-api.git
  #   ports:
  #     - "8083:8080" # Remplacer <port_event_api> par le port désiré pour l'accès à Event API

  # membre-api:
    # build:
    #   context: https://github.com/Flintpop/si-membre-api.git
    # ports:
    #   - "8084:8080" # Remplacer <port_membre_api> par le port désiré pour l'accès à Membre API

  # core-api:
  #   build: 
  #     context: https://github.com/Flintpop/si-core-api.git
  #   ports:
  #     - "8085:8080" # Remplacer <port_core_api> par le port désiré pour l'accès à Core API

  vuejs-client:
    build: 
      context: https://github.com/AntoineT01/si-client.git
    ports:
      - "8080:8080"
    networks:
      - ubo-network
    # depends_on:
    #   - si-membre-api

  mariadb:
    image: mariadb:11.3.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uboeventflow_bdd
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - mariadb-data:/var/lib/mysql
    networks:
      - ubo-network

  mongo:
    build:
      context:
        ./dockerMongodb
    ports:
      - "27017:27017"
    networks:
      - ubo-network

networks:
  ubo-network:
    external: true

volumes:
  mariadb-data:
  # mongodb-data:
